---
galaxy_info:
  role_name: sap_create_vm
  namespace: community
  author: Nils Koenig
  description: Use this role to create a virtual machine ready for SAP workloads (e.g. HANA, Netweaver) on an Red Hat OpenShift Virtualization (OCPv) platform. Note that there is no official support statement from SAP regarding this VM.
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: OpenShift
      versions:
        - 4.12
  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
