---
- name: "Create namespace {{ sap_create_vm_namespace }}"
  kubernetes.core.k8s:
    name: "{{ sap_create_vm_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Delete VMs using Kubernetes module
  kubernetes.core.k8s:
    name: "{{ sap_create_vm_namespace }}"
    template:
      path: "{{ sap_create_vm_template }}"
    state: absent
  loop: "{{ sap_create_vm_names }}"
  when: sap_create_vm_delete_vms == true

- name: Create VMs using Kubernetes module
  kubernetes.core.k8s:
    name: "{{ sap_create_vm_namespace }}"
    template:
      path:  "{{ sap_create_vm_template }}" 
    state: present
  loop: "{{ sap_create_vm_names }}"

