---
- name: "Download rhel {{ sap_create_vm_rhel_version }} image"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        namespace: openshift-virtualization-os-images
        name: rhel-{{ sap_create_vm_rhel_version }}
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
      spec:
        source:
          registry:
            url: "docker://registry.redhat.io/rhel8/rhel-guest-image:{{ sap_create_vm_rhel_version }}"
            pullMethod: node
        storage:
          resources:
            requests:
              storage: 10Gi
