- name: Create Tempdir
  ansible.builtin.tempfile:
    state: directory
    suffix: "_{{ ansible_role_name }}"
  register: _tmpdir

- name: Set fact for tmpdir
  ansible.builtin.set_fact:
    _tmpdir: "{{ _tmpdir }}"

#- name: Install dnspython
#  ansible.builtin.command: pip3 install dnspython
#  become: yes

#- name: "Get IP address for {{ dude_machine_name }}"
#  ansible.builtin.set_fact:
#    dude_sap_ip: "{{ lookup('community.general.dig', '{{ dude_machine_name }}.{{ vm_fqdn }}') }}"

#- name: Clear SSH known_hosts (hostname)
#  ansible.builtin.command: ssh-keygen -R "{{ dude_machine_name }}.{{ vm_fqdn }}"
#  ignore_errors: yes

#- name: Clear SSH known_hosts (IP)
#  ansible.builtin.command: ssh-keygen -R "{{ dude_sap_ip }}"
#  ignore_errors: yes
